"""Auto migration

Revision ID: 3b234d768432
Revises: 7b135fec0cde
Create Date: 2025-08-02 00:11:43.370336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3b234d768432'
down_revision: Union[str, Sequence[str], None] = '7b135fec0cde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
