version: '3.9'
services:
  msa-redis-service:
    container_name: msa_redis_container
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes:
      - ../docker-volumes/cache:/data

  msa-mongodb-service:
    container_name: msa_mongodb_container
    image: mongo:7.0.2
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ../docker-volumes/data:/data/db

  msa-mysql-service:
    container_name: msa_mysql_container
    image: mysql:9
    # command: ["mysqld", "--mysql-native-password=ON"]
    restart: always
    environment:
      - MYSQL_USER=labadmin
      - MYSQL_DATABASE=msa_auth
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_PASSWORD=root123
    ports:
      - '3306:3306'
    volumes:
      - ../docker-volumes/mysql:/var/lib/mysql
    networks:
      - es-network 

  msa-postgres-service:
    container_name: msa_postgres_container
    image: postgres:16.3
    restart: always
    environment:
      - POSTGRES_USER=labadmin
      - POSTGRES_PASSWORD=root123
      - POSTGRES_DB=msa_reviews
    ports:
      - '5432:5432'
    volumes:
      - ../docker-volumes/postgres:/var/lib/postgresql

  msa-rabbitmq-service:
    container_name: msa_rabbitmq_container
    image: rabbitmq:3.13-rc-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=labadmin
      - RABBITMQ_DEFAULT_PASS=root123
    ports:
      # AMQP protocol port
      - '5672:5672'
      # Management UI, RabbitMQ Dashboard
      - '15672:15672'
    networks:
      - es-network

  msa-elasticsearch-service:
    container_name: msa_elasticsearch_container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    restart: always
    environment:
      - ES_JAVA_OPTS=-Xmx1g -Xms1g
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.authc.api_key.enabled=true
      - xpack.monitoring.collection.enabled=true
      - xpack.security.enrollment.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9300:9300
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
      # - ../docker-volumes/esdata:/usr/share/elasticsearch/data
    networks:
      - es-network

  msa-kibana-service:
    container_name: msa_kibana_container
    image: docker.elastic.co/kibana/kibana:8.10.4
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=["http://msa_elasticsearch_container:9200"]
    ports:
      - 5601:5601
    networks:
      - es-network
    volumes:
      - ../configurations/kibana.yml/:/usr/share/kibana/config/kibana.yml:ro
    depends_on: 
      - msa-elasticsearch-service

  msa-notification-service:
    container_name: msa_notification_container
    build:
      context: ../server
      dockerfile: notification-service/Dockerfile.development
    restart: always
    ports:
      - 4001:4001
    volumes:
      - ../server/notification-service:/application/notification-service
      - ../server/server-shared:/application/server-shared
    working_dir: /application/notification-service
    command: >
      uvicorn server:app --host 0.0.0.0 --port 4001 --reload
    env_file: ../server/notification-service/.env
    environment:
      - DEVELOPMENT=True
      - JWT_SECRET=your_secret_key_here
      - JWT_ALGORITHM=
      - SECRET_KEY_ONE=super_secret_key_1
      - SECRET_KEY_TWO=super_secret_key_2
      - CLIENT_URL=http://example.com
      - SERVER_IP=0.0.0.0
      - SERVER_PORT=4001
      # Database and Redis configuration
      - POSTGRES_DATABASE_URL=
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - REDIS_URL=
      # RabbitMQ configuration
      - RABBITMQ_ENDPOINT=amqp://labadmin:root123@msa_rabbitmq_container:5672
      # Mail configuration
      - MAIL_USERNAME=Abdul Stroman
      - MAIL_PASSWORD=e1xCsBwCzQ4VbeNNye
      - MAIL_SERVER=smtp.ethereal.email
      - MAIL_PORT=587
      - MAIL_FROM=abdul.stroman62@ethereal.email
      - MAIL_FROM_NAME=Louvenia
      - DOMAIN=example.com
      # Elasticsearch configuration
      - ENABLE_ES=1
      - ELASTICSEARCH_URL=http://elastic:admin1234@msa_elasticsearch_container:9200
      # Application Performance Monitoring (APM) configuration
      - ENABLE_APM=1
      - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - msa-elasticsearch-service
      - msa-rabbitmq-service
    networks:
      - es-network

  msa-auth-service:
    container_name: msa_auth_container
    build:
      context: ../server
      dockerfile: auth-service/Dockerfile.development
    restart: always
    ports:
      - 4002:4002
    volumes:
      - ../server/auth-service:/application/auth-service
      - ../server/server-shared:/application/server-shared
    working_dir: /application/auth-service
    command: >
      uvicorn server:app --host 0.0.0.0 --port 4002 --reload
    env_file: ../server/auth-service/.env
    environment:
      - DEVELOPMENT=True
      - JWT_SECRET=your_gateway_secret_key_here
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRATION_TIME=3600  # in seconds
      - JWT_REFRESH_EXPIRATION_TIME=86400  # in seconds
      # Secret keys for various services
      - SECRET_KEY_ONE=super_secret_key_1
      - SECRET_KEY_TWO=super_secret_key_2
      - API_GATWAY_URL=http://0.0.0.0:4000
      - CLIENT_URL=http://example.com
      - SERVER_IP=0.0.0.0
      - SERVER_PORT=4002
      # Cloudinary Configuration
      - CLOUDINARY_URL=cloudinary://<your_api_key>:<your_api_secret>@dw3qovmta
      - CLOUDINARY_CLOUD_NAME=cloudinary://<your_api_key>:<your_api_secret>@dw3qovmta
      - CLOUDINARY_API_KEY=817183376894966
      - CLOUDINARY_API_SECRET=817183376894966
      # Database and Redis configuration
      - MYSQL_URL=mysql+asyncmy://labadmin:root123@msa_mysql_container:3306/msa_auth 
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - REDIS_URL=
      # RabbitMQ configuration
      - RABBITMQ_ENDPOINT=amqp://labadmin:root123@msa_rabbitmq_container:5672
      # Elasticsearch configuration
      - ENABLE_ES=1
      - ELASTICSEARCH_URL=http://elastic:admin1234@msa_elasticsearch_container:9200
      # Application Performance Monitoring (APM) configuration
      - ENABLE_APM=1
      - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
      - ELASTIC_APM_SECRET_TOKEN=

    depends_on:
      - msa-elasticsearch-service
      - msa-mysql-service
      - msa-rabbitmq-service
    networks:
      - es-network
  msa-api-gateway-service:
    container_name: msa_api_gateway_container
    build:
      context: ../server
      dockerfile: api-gateway-service/Dockerfile.development
    restart: always
    ports:
      - 4000:4000
    volumes:
      - ../server/api-gateway-service:/application/api-gateway-service
      - ../server/server-shared:/application/server-shared
    working_dir: /application/api-gateway-service
    command: >
      uvicorn server:app --host 0.0.0.0 --port 4000 --reload
    env_file: ../server/api-gateway-service/.env
    environment:
      # This file is used to configure environment variables for the application.
      # It should not be committed to version control.
      - DEVELOPMENT=True
      - JWT_TOKEN=your_secret_key_here
      - GATEWAY_JWT_TOKEN=your_gateway_secret_key_here
      - SECRET_KEY_ONE=super_secret_key_1
      - SECRET_KEY_TWO=super_secret_key_2
      - SERVER_IP=0.0.0.0
      - SERVER_PORT=4000
      # Redis configuration
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - REDIS_URL=
      # Other service URLs
      - CLIENT_URL=http://localhost:3000
      - AUTH_BASE_URL=http://msa_auth_container:4002
      - USERS_BASE_URL=http://localhost:4003
      - CATALOG_BASE_URL=http://localhost:4004
      - MESSAGE_BASE_URL=http://localhost:4005
      - ORDER_BASE_URL=http://localhost:4006
      - REVIEW_BASE_URL=http://localhost:4007
      - REDIS_HOST=redis://localhost:6379
      # Elasticsearch configuration
      - ENABLE_ES=1
      - ELASTICSEARCH_URL=http://elastic:admin1234@msa_elasticsearch_container:9200
      # Application Performance Monitoring (APM) configuration
      - ENABLE_APM=0
      - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - msa-elasticsearch-service
    networks:
      - es-network

volumes:
  esdata:
    driver: local
      
networks:
  es-network:
    name: es-network
    driver: bridge
